spring:
  application:
    name: notification-service

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mcs-notification?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: r00t
#    hikari:
#      pool-name: HikariPool-1
#      auto-commit: true
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    partition:
      user-dlt: 1
    replication:
      user-dlt: 2
    group:
      user: user_notification_group
    topic:
      user: user_notification_topic
      user-dlt: user_notification_dlt_topic

    bootstrap-servers:
      - localhost:29092
      - localhost:29093
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 8081