server:
  port: 8080

spring:
  application:
    name: bff-service

  cache:
    type: redis

  graphql:
    graphiql:
      enabled: true
      path: /graphiql

  kafka:
    partition:
      room: 2
      booking-room: 2
    replication:
      room: 2 #2 kafka brokers
      booking-room: 2
    topic:
      room: room_topic
      booking-room: booking_room_topic
      booking-room-reply: booking_room_reply_topic
    bootstrap-servers:
      - localhost:29092
      - localhost:29093
    producer:
      acks: -1
      retries: 5 # re-send 5 times
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        "request.timeout.ms": "300" # if in 3s can not send message => fail
        "enable.idempotence": "true"
        "max.in.flight.requests.per.connection": "5"

  data:
    redis:
      host: localhost
      port: 6379
      password: admin

  cloud:
    openfeign:
      client:
        decode-slash: true

client:
  user-client:
    name: user-client
    url: localhost:8082
  room-client:
    name: room-client
    url: localhost:8025
  booking-client:
    name: booking-client
    url: localhost:8083

logging:
  level:
    root: "info"
    org.springframework.web: "debug"
    org.hibernate: "error"