spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mcs-user?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: r00t
    hikari:
      pool-name: HikariPool-1
      auto-commit: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    partition:
      user: 2
    replication:
      user: 2 #2 kafka brokers
    topic:
      user: user_notification_topic
    bootstrap-servers:
      - localhost:29092
      - localhost:29093
    producer:
      acks: -1
      retries: 5 # re-send 5 times
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        "request.timeout.ms": "300" # if in 3s can not send message => fail
        "enable.idempotence": "true"
        "max.in.flight.requests.per.connection": "5"

axon:
  eventhandling:
    processors:
      NAME_OF_THE_PROCESSOR:
        mode: tracking
  axonserver:
    context: default
    enabled: true
    servers: localhost

client:
  keycloak-client:
    name: keycloak-client
    url: localhost:7080

server:
  port: 8082